export type Locale = 'en' | 'tr';

const en = {
  chips: [
    '📁 final_v2_FINAL_really.mp4',
    '"just one more small change?"',
    '📊 payments_2026 (3).xlsx',
    '₺ still owed: ???',
    'did I send V3 or V4?',
    'client_notes_old.txt',
    '00:43 → "make it pop"',
    '47 unread messages',
  ],
  chaosSub: 'Clients. Versions. Payments.',
  chaosWords: ['Freelance', 'work', 'gets'],
  chaosAccent: 'messy.',
  tagline: 'Work, revisions and payments —',
  taglineAccent: 'in one calm place.',
  steps: ['01 Work', '02 Revisions', '03 Payments'],
  hints: ['local · your machine', 'works on closed periods too', 'partial or full'],
  nav: ['Dashboard', 'Clients', 'Work Items', 'Periods', 'Settings'],
  workTitle: 'Every client.',
  workAccent: 'Every period.',
  workBody: 'Fixed prices per client, stages per job, a summary you can read at a glance.',
  crumb: 'Clients › Northwind Studio',
  strip: ['Total', 'Paid', 'Due', 'Open revisions'],
  rows: [
    ['Launch video edit', 'Completed · 1 × ₺8,000'],
    ['Product teaser', 'In progress · 2 × ₺4,000 · ×1.5 rush'],
    ['Thumbnail set', 'Completed · 3 × ₺250'],
    ['Color grade', 'In progress · stages 2 / 4'],
  ],
  revTitle: 'Every version.',
  revAccent: 'Every note.',
  revBody: "Know what you sent, what they asked for — and what's actually new scope.",
  versionsLabel: 'Versions · Product teaser',
  dates: ['12 Sep', '18 Sep', '24 Sep'],
  status: ['Draft', 'Sent', 'Approved'],
  flow: 'Draft → Sent → Approved',
  feedbackLabel: 'Client feedback',
  feedback: ['Warmer color on the intro shot', 'Can we add a 15s vertical cut?'],
  tags: ['Revision', 'New scope'],
  balanceLabel: 'Northwind Studio · balance due',
  payments: ['Advance', 'Final payment'],
  closed: 'Period closed.',
  closedAccent: 'A new one is already open.',
  proofTitle: 'Built to stay',
  proofAccent: 'out of your way.',
  cards: [
    ['Languages', '4', 'EN · TR · DE · RU'],
    ['Reports', 'TXT · XLSX', 'one click, per period'],
    ['Backup', '1 file', 'validated before restore'],
    ['Cloud', '0', 'no account · no tracking'],
  ],
  ctaLine: 'Free & open source.',
  ctaAccent: 'Yours.',
  footer: 'Windows · GPL-3.0 · no account, no cloud',
  thousands: ',',
};

const tr: typeof en = {
  chips: [
    '📁 final_v2_SON_bu.mp4',
    '"küçük bir değişiklik daha?"',
    '📊 odemeler_2026 (3).xlsx',
    '₺ kalan: ???',
    "V3'ü mü V4'ü mü göndermiştim?",
    'musteri_notlari_eski.txt',
    '00:43 → "biraz daha canlı"',
    '47 okunmamış mesaj',
  ],
  chaosSub: 'Müşteriler. Versiyonlar. Ödemeler.',
  chaosWords: ['Freelance', 'iş', 'kolayca'],
  chaosAccent: 'dağılır.',
  tagline: 'İş, revizyon ve ödeme —',
  taglineAccent: 'tek sakin yerde.',
  steps: ['01 İşler', '02 Revizyonlar', '03 Ödemeler'],
  hints: ['yerel · kendi bilgisayarın', 'kapalı dönemlerde de çalışır', 'kısmi ya da tam'],
  nav: ['Özet', 'Müşteriler', 'İşler', 'Dönemler', 'Ayarlar'],
  workTitle: 'Her müşteri.',
  workAccent: 'Her dönem.',
  workBody: 'Müşteriye özel sabit fiyatlar, işe özel aşamalar, bir bakışta okunan özet.',
  crumb: 'Müşteriler › Northwind Studio',
  strip: ['Toplam', 'Ödenen', 'Kalan', 'Açık revizyon'],
  rows: [
    ['Lansman videosu kurgusu', 'Tamamlandı · 1 × ₺8.000'],
    ["Ürün teaser'ı", 'Devam ediyor · 2 × ₺4.000 · ×1,5 acil'],
    ['Thumbnail seti', 'Tamamlandı · 3 × ₺250'],
    ['Renk düzenleme', 'Devam ediyor · aşama 2 / 4'],
  ],
  revTitle: 'Her versiyon.',
  revAccent: 'Her not.',
  revBody: 'Ne gönderdiğini, ne istendiğini ve neyin aslında yeni kapsam olduğunu bil.',
  versionsLabel: "Versiyonlar · Ürün teaser'ı",
  dates: ['12 Eyl', '18 Eyl', '24 Eyl'],
  status: ['Taslak', 'Gönderildi', 'Onaylandı'],
  flow: 'Taslak → Gönderildi → Onaylandı',
  feedbackLabel: 'Müşteri geri bildirimi',
  feedback: ['Giriş planında daha sıcak renk', '15 sn’lik dikey kesim de eklenebilir mi?'],
  tags: ['Revizyon', 'Yeni kapsam'],
  balanceLabel: 'Northwind Studio · kalan tutar',
  payments: ['Avans', 'Son ödeme'],
  closed: 'Dönem kapandı.',
  closedAccent: 'Yenisi zaten açık.',
  proofTitle: 'Az ayar,',
  proofAccent: 'tam kontrol.',
  cards: [
    ['Diller', '4', 'TR · EN · DE · RU'],
    ['Raporlar', 'TXT · XLSX', 'dönem başına tek tık'],
    ['Yedek', '1 dosya', 'geri yüklemeden önce doğrulanır'],
    ['Bulut', '0', 'hesap yok · takip yok'],
  ],
  ctaLine: 'Ücretsiz ve açık kaynak.',
  ctaAccent: 'Senin.',
  footer: 'Windows · GPL-3.0 · hesap yok, bulut yok',
  thousands: '.',
};

export const copy = { en, tr };
export type Copy = typeof en;
